version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DOCKER_MYSQL_PASSWORD
      - MYSQL_DATABASE=$DOCKER_MYSQL_DATABASE
    ports:
      - $LOCAL_MYSQL_PORT:$DOCKER_MYSQL_PORT
    # network_mode: "host"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./test_dockerize
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $LOCAL_NODE_PORT:$DOCKER_NODE_PORT
    environment:
      - MYSQL_HOST=$EXT_DEV_MYSQL_HOST
      - MYSQL_PORT=$EXT_DEV_MYSQL_PORT
      - MYSQL_DATABASE=$EXT_DEV_DATABASE
      - MYSQL_USERNAME=$EXT_DEV_USERNAME
      - MYSQL_PASSWORD=$EXT_DEV_PASSWORD
    stdin_open: true
    tty: true

volumes:
  db:
